const actionTypes = {
    ADD_DRIVER_STANDINGS: 'ADD_DRIVER_STANDINGS',
    SET_TOP_DRIVERS_DATA: 'SET_TOP_DRIVERS_DATA',
    SET_TOP_CONSTRUCTORS: 'SET_TOP_CONSTRUCTORS',
    SET_NEXT_RACE_EVENT: 'SET_NEXT_RACE_EVENT',
    SET_DRIVERS_DATA: 'SET_DRIVERS_DATA'
};

export default actionTypes;