const actionTypes = {
    SET_NEXT_RACE_EVENT: 'SET_NEXT_RACE_EVENT',
    SET_DRIVERS_DATA: 'SET_DRIVERS_DATA',
    SET_CONSTRUCTORS_DATA: 'SET_CONSTRUCTORS_DATA',
    SET_TOP_DRIVERS_DATA: 'SET_TOP_DRIVERS_DATA',
    SET_TOP_CONSTRUCTORS_DATA: 'SET_TOP_CONSTRUCTORS_DATA',
    SET_TOP_CONSTRUCTORS_VISIBLE: 'SET_TOP_CONSTRUCTORS_VISIBLE',
    SAVE_WINDOW_POS: 'SAVE_WINDOW_POS'
};

export default actionTypes;